#!/bin/bash

source $OPENSHIFT_PHP_DIR/lib/util

echo "Deploying..."
build_config

# Uncomment the following line to use Composer and automatically install dependencies on deploy.
#
#cd $OPENSHIFT_REPO_DIR; composer install
