#!/bin/bash

# You can now directly use `composer install`
# This is just a backward compatibility support.
function install_dependencies() {
    echo "Installing dependencies..."
    cd $1; composer install
}
